export const meetingRoute={
	path:'/oa/meeting',
	meta:{
		title:'会议管理',
		nav:true,
		layout:'slider'
	},
	component:()=>import('./index'),
	children:[
		{
			path:'/oa/meeting',
			name:"totalMeeting",
			meta:{
				title:'全部会议',
				nav:true,
				layout:'slider'
			},
			component:()=>import('./list')
		},
		{
			path:"/oa/meeting/create",
			name:'createMeeting',
			meta:{
				title:'会议预定',
				nav:true,
				layout:'slider'
			},
			component:()=>import('./create')
		},{
			path:'/oa/meeting/detail',
			name:'detailMeeting',
			meta:{
				title:"行政事务",
				nav:false,
				layout:'slider'
			},
			component:()=>import('./detail')
		}
	]
}