export let petRouter={
	path:"/basic/pet",
	name:"pet",
	meta:{
		title:"宠物档案",
		nav:true,
		authRequired:true,
		layout:'slider',
		icon:'el-icon-user'
	},
	component:()=>import('./index'),
	children:[
		{
			path:'/basic/pet',
			name:'petlist',
			meta:{
				title:"全部档案",
				nav:true,
				authRequired:true,
				layout:'slider'
			},
			component:()=>import('./list')
		},
		{
			path:'/basic/pet/create',
			name:'createpet',
			meta:{
				title:'创建档案',
				nav:true,
				authRequired:true,
				layout:'slider'
			},
			component:()=>import('./create')
		},
		{
			path:'/basic/pet/detail',
			name:'detailpet',
			meta:{
				title:'宠物详情',
				nav:false,
				authRequired:true,
				layout:'slider'
			},
			component:()=>import('./detail')
		}
	]
}